name: docusaurus

on:
  push:
    branches:
      - push-action-test
jobs:
  push_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
