name: Next Release

on:
  push:
    branches:
      - workspaces
    paths:
      - package/**

jobs:
  publish-next:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: '0'
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Prepare git
        run: |
          git config --global user.name "Vishal Narkhede"
          git config --global user.email "vishal@getstream.io"
      - name: Installation
        run: yarn && yarn workspaces run install
      - name: Lint
        run: yarn workspaces run lint-fix
      - name: Publish Next release
        run: yarn workspaces run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
